version: '3.1'

services:
  wordpress:
    image: wordpress
    ports:
      - "127.0.0.1:8890:80"
    env_file:
      - .env.wp
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/themes/finn
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/themes/finn
    env_file:
      - .env.wp
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mysql:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

volumes:
  wordpress_data:
