name: Deploy to fabian-kaegy.com - Spinup WP

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  install:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install NPM Dependencies
        run: npm install
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build Files
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_SSH_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_SERVER_IP }}
          # Remote user
          REMOTE_USER: ${{ secrets.DEPLOYMENT_SSH_USERNAME }}
          # Target directory in the format of `sites/${domain}/files/wp-content/...`
          TARGET: ${{ secrets.DEPLOYMENT_TARGET_FOLDER }}
          # An array of folder to exclude
          EXCLUDE: node_modules, .git
